### ISSUE TITLE
Confirm before the state is changed. 

### ISSUE THREAD

**Issue by vikram-santhalia** [servergrove/NgSwitchery#19]
In my use case, enabling or disabling the button makes a call to server, so I want to add a confirm window before the state is changed asking the user if he/she really wants to change the state.

So I added a directive:

.directive('ngConfirmClick', [
  function(){
    return {
      priority: 10,
      restrict: 'A',
      link: function(scope, element, attrs){
        element.bind('click', function(e){
          var message = attrs.ngConfirmClick;
          if(message && !confirm(message)){
            e.stopImmediatePropagation();
            e.preventDefault();
          }
        });
      }
    }
  }
])

<input type="checkbox" ng-confirm-click ng-model="switches.basic" ui-switch="{color: '#2ccb75', secondaryColor: '#fa9191'}" />

But this directive doesnt work. It doesnt gets called at all. Can you help me if this can be achieved.

**Comment by aramonc** [comment]
binding to the `change` event might work better. however, there's no guarantee of if the event listener will be bound before or after the Switchery event listeners.

Unfortunately I have been pretty busy lately & have not been able to add time to this project. You may want to check out the CSS solution described in the README & create your own directive using that.
