### ISSUE TITLE
How it use with requirejs?

### ISSUE THREAD

**Issue by MikeBazhenov** [servergrove/NgSwitchery#20]
I include switchery.js before initialization ngSwtchery and switchery not plugged into window why?

```
switcher = new $window.Switchery(elem[0], options); //undefined is not a function
```

**Comment by aramonc** [comment]
This lib doesn't use requireJS. You have to add Switchery as a script tag in your header before even AngularJS.

**Comment by MikeBazhenov** [comment]
@aramonc i use requirejs for organize application

**Comment by aramonc** [comment]
unfortunately that's currently not supported by us. As it is I'm having a hard time keeping up with PRs because this project is not being used by us anymore. 

You may want to try to do this with [pure css](https://github.com/abpetkov/switchery/issues/13) and avoid the extra dependency.

**Comment by MikeBazhenov** [comment]
@aramonc ok thanks
