### ISSUE TITLE
sizes

### ISSUE THREAD

**Issue by maeishoj** [servergrove/NgSwitchery#24]
Hello, and thanks for this nice directive!

How would you go about changing the size of the swtich?

**Comment by olmoser** [comment]
`ui-switch="{color:'#5C9C4D', size: 'small'}"`

works for me

**Comment by swapnilchincholkar** [comment]
Are you looking for https://github.com/abpetkov/switchery#user-content-sizes?

**Comment by lcarva** [comment]
This is due to an outdated version of switchery being used. Can the library be updated?

**Comment by OtaK** [comment]
Closed with #28 ;)
