### ISSUE TITLE
Bower // Npm install?

### ISSUE THREAD

**Issue by ibbatta** [servergrove/NgSwitchery#36]
Why don't you made a bower || npm install of this?

**Comment by aramonc** [comment]
There is a bower install, but I haven't had time to pay much attention to this library. I am also not a JavaScript developer & the only person capable of maintaining this right now. Unfortunately I'm not the repo owner & don't work for the company anymore. Your best bet is to use one of the forks.

**Comment by ibbatta** [comment]
Thanks 👍
